config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :transactions
  resources :categories

  match 'transactions/filter_transactions', via: [:get, :post], as: 'filter_transactions'

  root to: "transactions#index"

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions

  belongs_to :user  

  validates :name_category, presence: true

  def self.colors
    ['Escolha uma cor','red','blue','yellow','green', 'mediumslateblue', 'brown']
end

  def self.total
    if self.situacao == true 
    self.sum(:value) - params[:value]  
    else
      self.sum(:value)
    end
  end

  scope :by_category, -> category { where(evento: category)}
  scope :sum_value, -> { map{ |p| p.value }.sum.to_i }

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = current_user.category
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Categoria criada com sucesso." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Categoria atualizada com sucesso" }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Categoria excluida com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name_category, :priority)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
      <h4 class="alert-heading mb-3">ERRO</h4>
      <ul>
        <% category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-12">
    <%= form.label :nome_da_categoria %>
    <%= form.text_field :name_category , class: 'form-control'%>
  </div>

  <div class="row">

    <div class="form-group col-6">
    <%= form.label :selecione_uma_etiqueta %>
    <%= form.select :priority, options_for_select(Category.colors, @category.priority),{include_blank:false, requerid: false} , class: "form-control select"%>
    </div>

  <div class="form-group mt-4">
    <%= form.submit 'Registrar', class:'btn btn-success'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container mt-5">

<h1>Edição de categoria</h1>

<%= render 'form', category: @category %>

</div>

app/views/categories/index.html.erb
<div class="container mt-5">

<h1>Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name category</th>
      <th scope="col">Priority</th>
      <th scope="col"th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name_category %></td>
        <td><%= category.priority %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


</div>

app/views/categories/new.html.erb
<div class="container mt-5">

<h1>Nova Categoria</h1>

<%= render 'form', category: @category %>

</div>

app/views/categories/show.html.erb
<div class='card-body'>
  <div class='row'>
    <p>
      <div class="form-group col-md-5">
        <strong>Nome da Categoria</strong>
        <%= @category.name_category %>
      </div>
    </p>

    <p>
      <div class='form-group col-md-5'>
        <strong>Ordem de Prioridade:</strong><Br>
        <%= @category.priority %>
      </div>
    </p>

    <div class="row mt-4">
      <div class="col-6">

        <%= link_to 'Editar', edit_category_path(@category), class: 'btn btn-warning w-100' %>
      </div> 
                
      <div class="col-6">
      
        <%= link_to 'Voltar', categories_path, class: 'btn btn-danger w-100' %>
      </div> 
    </div>
</div>