config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :transactions
  resources :categories

  match 'transactions/filter_transactions', via: [:get, :post], as: 'filter_transactions'

  root to: "transactions#index"

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = current_user.transactions
    @categories = Category.where(user:current_user)
 
    @categories = @categories.where("lower(categories.name_category) LIKE ?", "%#{params[:filter].downcase}%") if params[:filter].present?

    @Appetizer = @transactions.where(situation: true).sum(:value)
    @withdraws = @transactions.where(situation: false).sum(:value)
    @balance =   @Appetizer + (@withdraws)

  end

  def filter_transactions
    
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    #binding.pry
    @transaction.situation == true  ? @transaction.value = @transaction.value.to_i * -1 : @transaction.value 
    @transaction.user = current_user

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transação registrada com sucesso." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    #@transaction.situation == true  ? @transaction.value = @transaction.value.to_i * -1 : @transaction.value 
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "Transação atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transação excluida com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:name_transaction, :value, :date_transaction, :situation, :description, :category_id)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
      <h4 class="alert-heading mb-3">ERRO</h4>
      <ul>
        <% transaction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group col-sm-12">
    <%= form.label :nome_da_trasanção%>
    <%= form.text_field :name_transaction, class: 'form-control' %>
  </div>

  <div class="row">

    <div class="form-group col-6">
      <%= form.label :valor_da_transação %>
      <%= form.number_field :value, step: "0.01", require: true,  class: 'form-control' %>
    </div>

    <div class="form-group col-6">
      <%= label_tag "Data da transação" %>
      <%= form.date_field("date_transaction", value: Date.today, class: 'form-control') %>
    </div>

  </div>

  <div class="row">
    <div class="col-6">
      <%= form.radio_button :situation, 'true',autocomplete:"off" ,id:"danger-outlined",class:"btn-check", checked:true%>
      <%= form.label "Saidas", for:"danger-outlined",class:"btn btn-outline-danger   w-100 p-3 mt-3" %>
    </div>
    <div class="col">
      <%= form.radio_button :situation, 'false',autocomplete:"off",id:"success-outlined",class:"btn-check" %>
      <%= form.label "Entradas", for:"success-outlined",class:"btn btn-outline-success w-100 p-3 mt-3" %>
    </div>
  </div>
 
  <div class="form-group col-sm-12">
    <%= form.label :categoria %>
    <%= form.select :category_id, options_from_collection_for_select(Category.where(user_id:current_user), 'id', 'name_category'), {include_blank: true, requerid: true}, class: 'form-control ' %>
  </div>

  <div class="form-group col-sm-12">
    <%= form.label "Descrição", for:"textarea" %>
    <%= form.text_area :description, size: "25X25", class: "form-control", id: "textarea" %>
  </div>

  <div class="form-group mt-4">
    <%= form.submit 'Registrar', class:'btn btn-success'%>
  </div>
    
  </div>





  
<% end %>

app/views/transactions/edit.html.erb
<div class="container mt-5">


<h1>Editando transação</h1>

<%= render 'form', transaction: @transaction %>


</div>

app/views/transactions/index.html.erb
<main>
  <div class='header-transactions'>
    <h2>Transações</h2>
    <%#= form_tag transactions_path, method: 'get',class:"" do %>
      <%#= select(:person, :city_id, [['JANEIRO', 1], ['FEVEREIRO', 2]]) %>    
    <%#end%>
  </div>

 <div class="cards-money">
    <div class="card-money">
      <div> 
        <p class="controll">ENTRADAS</p>
        <%= image_tag("income.svg", class: "") %>
      </div>
        <h3><%= number_to_currency(@withdraws, :unit => "R$") %></h3>
    </div>

    <div class="card-money">
      <div> 
        <p class="controll">SAIDAS</p>
        <%= image_tag("outcome.svg", class: "") %>

      </div>
        <h3><%= number_to_currency(@Appetizer, :unit => "R$") %></h3>
    </div>

    <div class="card-money">
      <div> 
        <p class="controll whitecolor">SALDO</p>
        <%= image_tag("total.svg", class: "") %>
      </div>
        <h2 class="whitecolor"><%=number_to_currency(@balance, :unit => "R$") %></h2>
    </div>
  </div>
</main>

  <% @categories.each do |category| %>
          
    <div class="btn-collapse">
      <a class="" data-bs-toggle="collapse" href="#collapse<%=category.id%>" role="button" aria-expanded="false" aria-controls="collapseExample">
        <div class="category-transaction">
          <div>
            <div class="color" >
              <span style="background-color:<%=category.priority%>"></span>
              <p><%= category.name_category%></p>
              
            </div>
            <p> <%=category.transactions.count%>
                <%=category.transactions.count <= 1 ? 'transação' : 'transações' %> 
          </div>
          <H3> <%= number_to_currency(category.transactions.total, :unit => "R$") 
          %></H3>
        </div>

        <span>
            <%= image_tag("arrow-down.svg", class: "") %>
        </span>
      </a>
    </div>

    <%category.transactions.each do |transactions|%>           
      <div class="collapse" id="collapse<%=category.id%>">

        <div class="transaction-info">
          
          <div class="card-transaction">
            <div class="content-actions">

              <%= link_to  transactions do%>
                <%= image_tag("view.png", class: "yellow") %>
              <%end%>

              <%= link_to edit_transaction_path(transactions) do %>
                  <%= image_tag("edit.png", class: "") %>
              <%end%>

              <%= link_to transactions, method: :delete, data: { confirm: 'Voce tem certeza ?' } do %>
                  <%= image_tag("cancel.png", class: "") %>
              <%end%>

            </div>
              <p><%=transactions.name_transaction.truncate(20)%></p>
          </div>

          <div>
            <H3 style="color:<%=transactions.situation == true ? 'red' : 'green' %>">
            <%= number_to_currency(transactions.value, :unit => "R$") %></H3>
            
            <p><%= transactions.date_transaction ? l(transactions.date_transaction, formats: :casual, locale: :'pt-BR', default: '-') : l(transactions.created_at, formats: :casual, locale: :'pt-BR', default: '-')%></p> 
          </div>
        </div>  
      </div>
  <%end%>
<% end %>




 
 

    

    
 

app/views/transactions/new.html.erb
<div class="container mt-5">
<h1>Nova Transação</h1>

<%= render 'form', transaction: @transaction %>

</div>

app/views/transactions/show.html.erb
<div class="show">   
  <div class='card-body'>
    <div class='row'>
      <p>
        <div class="form-group col-md-5">
          <strong>Nome da trasanção:</strong><Br>
          <p><%= @transaction.name_transaction.truncate(60)%></p>
        </div>
      </p>

      <p>
        <div class='form-group col-md-6'>
          <strong>Valor da transação:</strong><Br>
          <%=number_to_currency(@transaction.value, :unit => "R$")  %>
        </div>
      </p>

      <p>
        <div class='form-group col-md-6'>
          <strong>Data da transação:</strong><Br>
          <%=l(@transaction.date_transaction, formats: :casual, locale: :'pt-BR', default: '-')%>
        </div>
      </p>

      <p>
        <div class='form-group col-md-6'>
          <strong>Situação:</strong><Br>

          <%=@transaction.situation  == true ? "Retirada" : "Entrada"%>
        </div>
      </p>

      <p>
        <div class='form-group col-md-6'>
          <strong>Categoria:</strong><Br>
          <%= @transaction.category.name_category %>
        </div>
      </p>

      <p>
        <div class='form-group col-md-6'>
          <strong>Description:</strong><Br>
          <%= @transaction.description %>
        </div>
      </p>

      <div class="row mt-4">
        <div class="col-6">

          <%= link_to 'Editar', edit_transaction_path(@transaction), class: 'btn btn-warning w-100' %>
        </div> 
                  
        <div class="col-6">
        
          <%= link_to 'Voltar', transactions_path, class: 'btn btn-danger w-100' %>
        </div> 
        </div>
    </div>

  </div>
</div>