config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :transactions
  resources :categories

  match 'transactions/filter_transactions', via: [:get, :post], as: 'filter_transactions'

  root to: "transactions#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinancesKey</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  </head>

  <body>
  <% if current_user.present? %>
    <header>

      <div class="logo">
          <%= link_to transactions_path, class:"arrow" do %>
            <%= image_tag("backarrow.svg", class: "") %>
          <%end%>
      <%= link_to "Sair",destroy_user_session_path, method: :delete, class: "btn sair"  %>
      </div>
    
      <div class="new">
        <%= form_tag transactions_path, method: 'get',class:"" do %>
          <div class="filter d-flex">
            <%= text_field_tag :filter, params[:filter], class: "",placeholder: 'Procurar Categoria' %>

            <%= button_tag(value: 'commit', type: 'submit', class: 'btn btn-sge  mb-2') do%>
                <%= image_tag("loupe.png", style: "width:20px;heigth:20px") %>
          </div>
            
          <% end %>
        <%end%>
        <div class="d-flex w-100">
          <%= link_to '+ Transação', new_transaction_path ,class:"button"%>
          <%= link_to '+ Categoria', new_category_path ,class:"button"%>
        <div>
      <div>
    </header>
  <%end%>  
      <%= yield %>
<script src="/vendor/jquery/jquery.min.js"></script>
<script src="/vendor/bootstrap-growl-ifightcrime/jquery.bootstrap-growl.min.js"></script>


<%if notice %>
    <script>
    $.bootstrapGrowl("<%=notice%>", {
    ele: 'body', // which element to append to
    type: 'success', // (null, 'info', 'error', 'success')
    offset: {from: 'bottom', amount:20 },
    align: 'right', // ('left', 'right', or 'center')
    allow_dismiss: false,
    stackup_spacing: 10 // spacing between consecutively stacked growls.
    })
    </script>
<%end%>
  
  </body>

</html>